### ISSUE TITLE
Child containers may not be desired

### ISSUE THREAD

**Issue by darrencauthon** [cocowalla/Hangfire.StructureMap#3]
I'm still testing the fix, but I think there may times when an application should not use child containers.

The problem I hit is a block of code that relies heavily on a series of `async` calls.  I kept getting weird behaviors where things might seem to be fine, but then I might get errors trying to access disposed objects or disposed containers.  It took a while to figure out, but I traced it back to this library and its disposal of the container and related objects before they might actually be complete.

I thought the solution might be that I needed to be extra-careful about how await is used, or even hardcoding `.Wait()` within the code, but when I had jobs that initiated other jobs I came across more disposed object failures.  I just couldn't find a way to make it work.

There was one magic fix, though, and it was to stop the nested containers.  I replaced `StructureMapJobActivator` with one that did not use nested containers and that did not manually call dispose on the container.  I create one instance of my IoC container, and then I use just that instance forever.  And just like that, the application worked exactly as expected.

I know, I know, it might seem like the nested containers are safer, but I think that's a matter of how the IoC container is registered and used.  In my case, I tend to depend on `Func<IFoo>` over `IFoo`, as I want the dependency to be resolved as late as possible.  I also don't carry "state" objects in my IoC container, so every time I ask the IoC container for something, I get a brand-new instance.  Using the IoC container this way tends to take care of the concerns that would normally lead one to go down the nested container route.  (personally, I tend to think of nested containers as a smell)

It's pretty simple, here's an example 

``` c#
    public class SpecialStructureMapJobActivator : StructureMapJobActivator
    {
        private readonly IContainer container;

        public SpecialStructureMapJobActivator(IContainer container) : base(container)
        {
            this.container = container;
        }

        public override JobActivatorScope BeginScope()
        {
            return new StructureMapDependencyScope(container);
        }

        private class StructureMapDependencyScope : JobActivatorScope
        {
            private readonly IContainer container;

            public StructureMapDependencyScope(IContainer container)
            {
                this.container = container;
            }

            public override object Resolve(Type type)
            {
                return container.GetInstance(type);
            }
        }

```

and

``` c#
//GlobalConfiguration.Configuration.UseStructureMapActivator(container);
GlobalConfiguration.Configuration.UseActivator(new SpecialStructureMapJobActivator(container));
```

I'll make this into a formal pull request soon, but I wanted to give you a chance for any input.  I was thinking about adding an option to the existing code to allow users to toggle the use of the nested containers (defaulting to the original behavior).  I'll also document the toggle.  I'm doing so only to possibly help the next developer who gets caught with this issue.

**Comment by odinserj** [comment]
> I thought the solution might be that I needed to be extra-careful about how await is used, or even hardcoding .Wait() within the code, but when I had jobs that initiated other jobs I came across more disposed object failures. I just couldn't find a way to make it work.

All outstanding async operations should be completed before leaving a background job method. This _is_ the correct solution.

**Comment by darrencauthon** [comment]
> This is the correct solution.

That's not how it behaved, though.

If I were to abbreviate how this job worked, it would be:

``` c#
var data = await dependency1().GetSomeData();
template.Data["one"] = data;

var moreData = await dependency2().GetMoreData();
template.Data["two"] = moreData;

var evenMoreData = await dependency3().GetEvenMoreData();
template.Data["three"] = evenMoreData;

var response = await mailer().SendTemplate(template);
logger().NoteThatEmailWasSent(template, response);
```

This code was TDD'd, the tests are green, and it works successfully when run through Linqpad.  But when I run this code through Hangfire, it will bomb on `dependency2()`.  I alternated from the latest StructureMap 3.x and 4.x versions, with 3.x giving me a null reference error and 4.x giving me a disposed container error.  **Sometimes** it would fail on `dependency3()`, and once it went down to `mailer()` which would always fail.

I found that if I resolved all of the dependencies in the code immediately, like:

``` c#
var dep1 = dependency1();
var dep2 = dependency2();
var dep3 = dependency3();
var mailguy = mailer();
var log = logger();

// ...

log.NoteThatEmailWasSent(template, response);
```

Then everything would work up until the last `log.NoteThatEmailWasSent(template, response);`, which requires a lazy-loaded factory of `Func<DbContext>`.  The fact-of-the-matter:  The child container from StructureMap never made it to the end, so it was never around to finish the work.

My solution was to replace the job activator with one that didn't create child containers.  The container was always around, and everything works as expected.

In theory it shouldn't matter, but my applications have to run in reality.  Personally, I don't see the benefit in using child containers and taking over control of the disposal of objects, as I use my IoC container as a factory of objects that will get disposed whenever .Net wants.  It's my opinion that the IoC container should not hold anything where a developer ever would need to dispose.  

But that's just my opinion! :smile:  The problems I encountered happened across multiple StructureMap libraries and the latest Hangfire, and they started when I started using `async` methods.  What I wanted to offer was a pull request that might allow another dev to avoid the hours I lost debugging this issue, and to give them an option that might work better than to revamp how they approach IoC  I'm almost done with it, I'll push it around lunch.

**Comment by darrencauthon** [comment]
Oh, just to note:

I tend to make most of my classes dependent on `Func<IFoo>``over``IFoo``.  I prefer the lazy-loading, for reasons I won't get into here.  

I found the dependency resolution problems were mostly fixed by removing the `Func`'s, at least until I started dealing with the database (same half-resolution as above).  But I can't move forward with Hangfire if it requires an unverifiable way of writing code between Hangfire, StructureMap, and this library.  As far as I can remember, StructureMap has always supported this lazy-loading of dependencies.  If someone uses it and it blows up, then the answer isn't to tell devs not to do it -- I have to find an alternative to Hangfire. We can't go with unstable solutions.

**Comment by odinserj** [comment]
But you can't currently use `async Task` methods for background job (before Hangfire 1.6), and can't use the `await` keyword. 

Looks like you are using `async void` methods (this is an anti-pattern), right?

**Comment by darrencauthon** [comment]
I'm not using `async void`, but checking on the other...

**Comment by odinserj** [comment]
So how do you use the `await` keyword then? Can you post here the signature of your method that is passed to Hangfire?

**Comment by darrencauthon** [comment]
@odinserj Sorry for the delay, you bringing up the 1.6 matter made me look... sure enough, 1.5... and I got scared and had to run and double-check that things were working as I expected.  I've been using Hangfire in this way for a while now and it would be **disheartening** if it wasn't.  But I verified my logs and crossed them with an external email system we use, and everything checks out.  Whew.

But it doesn't mean I'm doing it right.  We have layers to this system, and I think I finally traced this call down.... it is:

``` c#
BackgroundJob.Enqueue(() => confirmation.Send(emailConfirmationRequest));
```

... which will fire off this method:

``` c#
public void Send(Request request)
{
    emailService.Send(emailRequestBuilder.Build(request));
}        
```

The email service interface is:

``` c#
public interface IEmailService
{
    Task<EmailResponse> Send(EmailRequest emailRequest);
}
```

I think if I changed the implementation to:

``` c#
        public void Send(Request request)
        {
            var response = emailService.Send(emailRequestBuilder.Build(request));
            response.Wait();
        }
```

Then this would probably fix the problem, as I bet `Dispose` is getting called when `Send` leaves scope, all while another thread is running and trying to do work against a container that was just destroyed.

**Comment by darrencauthon** [comment]
Oh, I should have mentioned... this is a one-off process, separate from the rest of the system.  So this particular problem is tied to only this, which is why all of my other emails work but this one does not.

That said... I still think building a separate child container for each job is more overhead than I think should be occurring.  When I set up my IoC container, it is essentially read-only.  Creating copies of it per job is more complicated than necessary.  I can _almost_ see some value in doing this in a framework like MVC where you have something specific with state that you can attach to, like a http request.  (I disagree, I think state doesn't belong in the IoC container, but I know it's common.)

But with Hangfire, we're talking about isolated jobs.  What possible need would one have to modify the container in any way during a job?  Why would the container ever be touched?  

I still think it could be helpful for others to know of the option, even if it's just documented in the readme.

**Comment by odinserj** [comment]
Yes, all the `async` methods should be awaited. 

> What possible need would one have to modify the container in any way during a job? Why would the container ever be touched?

Registrations may be untouched, but there are other data, that drive the following features:
1. Shared services (unit of work, connections, etc.) that have scope-based registrations. Within the same scope they should return the same service instance, and they should track them somehow.
2. Deterministic disposal. Scope track all the transient and scope-based disposable services, and dispose them when a scope ends.

> When I set up my IoC container, it is essentially read-only.

Only registrations are read-only. And some use-cases also require registrations to be modified, or even added based on context.

**Comment by darrencauthon** [comment]
Right, those are all reasons to use child containers... **IF** those are features you thread through the IoC container.  You can use unit of works, connections, etc without an IoC container.  There might be times when the container helps, and other times when it hurts.  In every application I've had a part in, it's hurt... but that's just my experience. :smile:

It seems you'd get deterministic disposal either way.  Even I don't manually call `.Dispose` on an object I don't need any longer, there's still a deterministic process that disposes of the object.  

In some cases, a single instance of an IoC container that serves only as a factory is the right call.  For those people, I'd like to help.

**Comment by odinserj** [comment]
> In some cases, a single instance of an IoC container that serves only as a factory is the right call. For those people, I'd like to help.

Which cases, @darrencauthon? Removing scopes for performance reasons is a premature optimization, it doesn't add any value for Hangfire job processing. I'm constantly run Hangfire under a profiler, and know that performance operations are most affected by storage.

**Comment by darrencauthon** [comment]
The case when a single instance of a container will work for an application, even across threads.

Like mine.  When this library creates a child container, that child container is not altered in any form for any of the processing of my application.  So, this child container is created only to be disposed manually.  

I'm not doing any optimization or removing scopes.  If I have a process that deserves a unit of work, for example, I just create the unit of work thru my IoC Container, run the code, and commit the transaction.  I just don't understand why the IoC container would have to hold that unit of work, **especially in a background job**.

I love tools like Hangfire and Sidekiq because they allow me to break up my work into incredibly small components.  All of my jobs follow SRP, doing one thing well and simply.  So if I have a job that says "do x with y and z" and y and z are simple variables, and x is a single operation... where's the scope to hold?  What's to dispose?

**Comment by darrencauthon** [comment]
Hmmm... thinking about other code I've read, I've sometimes seen unit of works that commit upon dispose.  It's like they say their last words before their death, and nobody has to call `Commit()`.

But I'd rather just be explicit and call ``Commit()`.  

Anyway, I don't mean to pester or argue, it's all good.  I love Hangfire and this library has been of great use.  And I anxiously await 1.6 which will officially support what... I'm already doing. :smile:  

Thanks,

**Comment by cocowalla** [comment]
Closing, as I assume 2+ years on that Hangfire has better support for async jobs.

Regarding performance, I still firmly believe nested containers are the right way to go here, and it's unlikely that they would ever be a bottleneck. If you have expensive dependencies, using the singlton scope might be an option, and you can always inject instances into the container and manage the lifecycle yourself.
