### ISSUE TITLE
.net core support

### ISSUE THREAD

**Issue by h4ckm03d** [cocowalla/Hangfire.StructureMap#5]
Is there any update to support .netcoreapp?

**Comment by cocowalla** [comment]
I didn't actually realise Hangfire supported .NET core yet, since I haven't had need to use them together yet. Happy to accept a pull request if this is something you want to tackle?

**Comment by h4ckm03d** [comment]
I'm already trying porting this library using .net core but can only enqueue task but I don't know why task cannot be executed.

**Comment by h4ckm03d** [comment]
@cocowalla 
for detailed problem already asked in http://stackoverflow.com/questions/43094418/is-there-any-better-way-using-hangfire-with-structuremap-on-asp-net-core/43476437#43476437

**Comment by h4ckm03d** [comment]
the problem is the SQL server that I use
